include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Enable additional strict rules for better pub.dev scoring
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
analyzer:
  exclude:
    # Exclude test files from certain const rules due to dynamic test values
    - test/**
