name: flutter_streaming_text_markdown
description: A Flutter package for displaying streaming text with Markdown support, featuring typing animations, word-by-word streaming, RTL support, and customizable fade-in effects.
version: 1.1.0
homepage: https://github.com/hooshyar/flutter_streaming_text_markdown
repository: https://github.com/hooshyar/flutter_streaming_text_markdown
issue_tracker: https://github.com/hooshyar/flutter_streaming_text_markdown/issues
documentation: https://github.com/hooshyar/flutter_streaming_text_markdown/blob/main/README.md
topics:
  - markdown
  - text
  - animation
  - streaming
  - rtl

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.6
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: 