name: flutter_streaming_text_markdown
description: A Flutter package for beautiful LLM text streaming with markdown support. Perfect for ChatGPT-like interfaces with typing animations, RTL support, and customizable effects.
version: 1.3.1
homepage: https://github.com/hooshyar/flutter_streaming_text_markdown
repository: https://github.com/hooshyar/flutter_streaming_text_markdown
documentation: https://github.com/hooshyar/flutter_streaming_text_markdown/blob/main/README.md
topics:
  - llm
  - streaming
  - markdown
  - animation
  - ai

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  gpt_markdown: ^1.1.2
  characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: 