name: flutter_streaming_text_markdown
description: A Flutter package for displaying streaming text with Markdown support
version: 0.0.1
homepage: https://github.com/hooshyar/flutter_streaming_text_markdown

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: 