import 'dart:collection';

import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:flutter/painting.dart';

import '../../theme/code_block_theme.dart';

/// Token kinds emitted by [CodeHighlighter].
enum _TokenKind {
  comment,
  string,
  number,
  keyword,
  type,
  function,
  annotation,
  punctuation,
  plain,
}

/// A pure-Dart regex-based syntax highlighter that produces a [TextSpan]
/// tree styled by a [CodeBlockTheme].
///
/// No span ever sets `backgroundColor` — backgrounds belong to the
/// container, so selections and parent decorations stay intact.
///
/// Results are memoized in a bounded LRU cache (~64 entries) keyed by
/// (language, code, theme, enabled), so repeated identical calls return
/// the cached span without re-tokenizing.
class CodeHighlighter {
  /// Creates a highlighter. Stateless - safe to use a `const` instance.
  const CodeHighlighter();

  /// Number of times real tokenization ran. Cache hits and disabled /
  /// empty inputs do not increment this.
  @visibleForTesting
  static int debugHighlightCount = 0;

  static const int _cacheLimit = 64;

  static final LinkedHashMap<_CacheKey, TextSpan> _cache =
      LinkedHashMap<_CacheKey, TextSpan>();

  /// Clears the memoization cache and resets [debugHighlightCount].
  @visibleForTesting
  static void debugClearCache() {
    _cache.clear();
    debugHighlightCount = 0;
  }

  /// Highlights [code] for [language] using [theme].
  ///
  /// When [enabled] is false — or [code] is empty — returns a single
  /// plain span in `theme.baseStyle`. Unknown or null languages use a
  /// generic fallback tokenizer; this method never throws on input shape.
  TextSpan highlight(
    String code, {
    String? language,
    required CodeBlockTheme theme,
    bool enabled = true,
  }) {
    if (!enabled || code.isEmpty) {
      return TextSpan(text: code, style: theme.baseStyle);
    }
    final key = _CacheKey(_normalize(language), code, theme, enabled);
    final cached = _cache.remove(key);
    if (cached != null) {
      _cache[key] = cached; // reinsert at the end → most-recently-used
      return cached;
    }
    debugHighlightCount++;
    final span = _tokenize(code, _specFor(key.language), theme);
    _cache[key] = span;
    if (_cache.length > _cacheLimit) {
      _cache.remove(_cache.keys.first);
    }
    return span;
  }

  // ---------------------------------------------------------------------
  // Tokenizer
  // ---------------------------------------------------------------------

  TextSpan _tokenize(String code, _LangSpec spec, CodeBlockTheme theme) {
    final spans = <TextSpan>[];
    var index = 0;
    for (final match in spec.pattern.allMatches(code)) {
      if (match.start > index) {
        spans.add(
          TextSpan(
            text: code.substring(index, match.start),
            style: theme.baseStyle,
          ),
        );
      }
      final kind = _classify(match, code, spec);
      spans.add(TextSpan(text: match.group(0), style: _styleFor(kind, theme)));
      index = match.end;
    }
    if (index < code.length) {
      spans.add(TextSpan(text: code.substring(index), style: theme.baseStyle));
    }
    return TextSpan(style: theme.baseStyle, children: spans);
  }

  _TokenKind _classify(RegExpMatch match, String code, _LangSpec spec) {
    if (match.namedGroup('comment') != null) return _TokenKind.comment;
    if (match.namedGroup('string') != null) return _TokenKind.string;
    if (match.namedGroup('number') != null) return _TokenKind.number;
    if (match.namedGroup('annotation') != null) return _TokenKind.annotation;
    if (match.namedGroup('tag') != null) return _TokenKind.keyword;
    if (match.namedGroup('punct') != null) return _TokenKind.punctuation;
    final ident = match.namedGroup('ident');
    if (ident != null) {
      final lookup = spec.caseInsensitiveKeywords ? ident.toLowerCase() : ident;
      if (spec.keywords.contains(lookup)) return _TokenKind.keyword;
      if (spec.builtins.contains(ident)) return _TokenKind.type;
      final first = ident.codeUnitAt(0);
      if (first >= 0x41 && first <= 0x5A) return _TokenKind.type; // A-Z
      if (match.end < code.length && code[match.end] == '(') {
        return _TokenKind.function;
      }
    }
    return _TokenKind.plain;
  }

  TextStyle _styleFor(_TokenKind kind, CodeBlockTheme theme) {
    switch (kind) {
      case _TokenKind.comment:
        return theme.baseStyle.copyWith(color: theme.commentColor);
      case _TokenKind.string:
        return theme.baseStyle.copyWith(color: theme.stringColor);
      case _TokenKind.number:
        return theme.baseStyle.copyWith(color: theme.numberColor);
      case _TokenKind.keyword:
        return theme.baseStyle.copyWith(color: theme.keywordColor);
      case _TokenKind.type:
        return theme.baseStyle.copyWith(color: theme.typeColor);
      case _TokenKind.function:
        return theme.baseStyle.copyWith(color: theme.functionColor);
      case _TokenKind.annotation:
        return theme.baseStyle.copyWith(color: theme.annotationColor);
      case _TokenKind.punctuation:
        return theme.baseStyle.copyWith(color: theme.punctuationColor);
      case _TokenKind.plain:
        return theme.baseStyle;
    }
  }

  // ---------------------------------------------------------------------
  // Language specs
  // ---------------------------------------------------------------------

  static String _normalize(String? language) =>
      _aliases[(language ?? '').trim().toLowerCase()] ?? 'generic';

  static _LangSpec _specFor(String normalized) =>
      _specs[normalized] ?? _specs['generic']!;

  static const Map<String, String> _aliases = {
    'dart': 'dart',
    'javascript': 'js',
    'js': 'js',
    'jsx': 'js',
    'typescript': 'js',
    'ts': 'js',
    'tsx': 'js',
    'python': 'python',
    'py': 'python',
    'java': 'java',
    'kotlin': 'kotlin',
    'kt': 'kotlin',
    'swift': 'swift',
    'go': 'go',
    'golang': 'go',
    'rust': 'rust',
    'rs': 'rust',
    'c': 'c',
    'cpp': 'c',
    'c++': 'c',
    'h': 'c',
    'cs': 'c',
    'csharp': 'c',
    'c#': 'c',
    'json': 'json',
    'yaml': 'yaml',
    'yml': 'yaml',
    'bash': 'bash',
    'sh': 'bash',
    'shell': 'bash',
    'zsh': 'bash',
    'sql': 'sql',
    'html': 'html',
    'xml': 'html',
  };

  /// `[^\s\S]` never matches — placeholder for token kinds a language lacks.
  static const String _never = r'[^\s\S]';

  static const String _cComments = r'//[^\n]*|/\*[\s\S]*?\*/';
  static const String _hashComment = r'#[^\n]*';
  static const String _htmlComment = r'<!--[\s\S]*?-->';

  static const String _dqString = r'"(?:\\.|[^"\\\n])*"';
  static const String _sqString = "'(?:\\\\.|[^'\\\\\\n])*'";
  static const String _backtickString = r'`(?:\\.|[^`\\])*`';

  static String _strings(List<String> variants) => variants.join('|');

  static const String _number =
      r'\b0[xX][\da-fA-F_]+\b'
      r'|\b0[bB][01_]+\b'
      r'|\b0[oO][0-7_]+\b'
      r'|\b\d[\d_]*(?:\.[\d_]+)?(?:[eE][+-]?\d+)?[fFlL]?\b';

  static _LangSpec _spec({
    String comments = _never,
    required String strings,
    Set<String> keywords = const {},
    Set<String> builtins = const {},
    String tag = _never,
    bool annotation = true,
    bool caseInsensitiveKeywords = false,
  }) => _LangSpec(
    pattern: RegExp(
      [
        '(?<comment>$comments)',
        '(?<string>$strings)',
        '(?<number>$_number)',
        '(?<annotation>${annotation ? r'@[A-Za-z_]\w*' : _never})',
        '(?<tag>$tag)',
        r'(?<ident>[A-Za-z_]\w*)',
        r'(?<punct>[^\w\s]+)',
      ].join('|'),
    ),
    keywords: keywords,
    builtins: builtins,
    caseInsensitiveKeywords: caseInsensitiveKeywords,
  );

  static final Map<String, _LangSpec> _specs = {
    'dart': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'abstract',
        'as',
        'assert',
        'async',
        'await',
        'break',
        'case',
        'catch',
        'class',
        'const',
        'continue',
        'covariant',
        'default',
        'deferred',
        'do',
        'dynamic',
        'else',
        'enum',
        'export',
        'extends',
        'extension',
        'external',
        'factory',
        'false',
        'final',
        'finally',
        'for',
        'get',
        'hide',
        'if',
        'implements',
        'import',
        'in',
        'interface',
        'is',
        'late',
        'library',
        'mixin',
        'new',
        'null',
        'on',
        'operator',
        'part',
        'required',
        'rethrow',
        'return',
        'sealed',
        'set',
        'show',
        'static',
        'super',
        'switch',
        'sync',
        'this',
        'throw',
        'true',
        'try',
        'typedef',
        'var',
        'void',
        'while',
        'with',
        'yield',
      },
      builtins: {
        'int',
        'double',
        'num',
        'bool',
        'String',
        'List',
        'Map',
        'Set',
        'Iterable',
        'Future',
        'Stream',
        'Object',
        'Function',
        'Never',
        'Record',
        'Symbol',
        'Duration',
        'DateTime',
        'RegExp',
        'Uri',
        'BigInt',
        'Runes',
      },
    ),
    'js': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'abstract',
        'any',
        'as',
        'async',
        'await',
        'boolean',
        'break',
        'case',
        'catch',
        'class',
        'const',
        'continue',
        'declare',
        'debugger',
        'default',
        'delete',
        'do',
        'else',
        'enum',
        'export',
        'extends',
        'false',
        'finally',
        'for',
        'from',
        'function',
        'get',
        'if',
        'implements',
        'import',
        'in',
        'infer',
        'instanceof',
        'interface',
        'keyof',
        'let',
        'namespace',
        'never',
        'new',
        'null',
        'number',
        'of',
        'private',
        'protected',
        'public',
        'readonly',
        'return',
        'satisfies',
        'set',
        'static',
        'string',
        'super',
        'switch',
        'symbol',
        'this',
        'throw',
        'true',
        'try',
        'type',
        'typeof',
        'undefined',
        'unknown',
        'var',
        'void',
        'while',
        'with',
        'yield',
      },
      builtins: {
        'Promise',
        'Array',
        'Map',
        'Set',
        'Record',
        'Partial',
        'Required',
        'Readonly',
        'Pick',
        'Omit',
        'Exclude',
        'Extract',
        'Object',
        'String',
        'Number',
        'Boolean',
        'Date',
        'RegExp',
        'Error',
        'JSON',
        'Math',
        'console',
      },
    ),
    'python': _spec(
      comments: _hashComment,
      strings: _strings([
        r'"""[\s\S]*?"""',
        "'''[\\s\\S]*?'''",
        _dqString,
        _sqString,
        _backtickString,
      ]),
      keywords: {
        'and',
        'as',
        'assert',
        'async',
        'await',
        'break',
        'class',
        'continue',
        'def',
        'del',
        'elif',
        'else',
        'except',
        'finally',
        'for',
        'from',
        'global',
        'if',
        'import',
        'in',
        'is',
        'lambda',
        'nonlocal',
        'not',
        'or',
        'pass',
        'raise',
        'return',
        'try',
        'while',
        'with',
        'yield',
        'True',
        'False',
        'None',
        'match',
        'case',
        'type',
      },
      builtins: {
        'int',
        'float',
        'str',
        'bool',
        'list',
        'dict',
        'set',
        'tuple',
        'frozenset',
        'bytes',
        'bytearray',
        'object',
        'type',
        'complex',
        'range',
        'slice',
        'Exception',
        'BaseException',
        'print',
        'len',
        'self',
        'cls',
      },
    ),
    'java': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString]),
      keywords: {
        'abstract',
        'assert',
        'boolean',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'continue',
        'default',
        'do',
        'double',
        'else',
        'enum',
        'extends',
        'final',
        'finally',
        'float',
        'for',
        'goto',
        'if',
        'implements',
        'import',
        'instanceof',
        'int',
        'interface',
        'long',
        'native',
        'new',
        'package',
        'private',
        'protected',
        'public',
        'record',
        'return',
        'sealed',
        'short',
        'static',
        'strictfp',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'try',
        'var',
        'void',
        'volatile',
        'while',
        'true',
        'false',
        'null',
        'yield',
        'permits',
      },
      builtins: {
        'String',
        'Integer',
        'Long',
        'Double',
        'Boolean',
        'Object',
        'List',
        'Map',
        'Set',
      },
    ),
    'kotlin': _spec(
      comments: _cComments,
      strings: _strings([r'"""[\s\S]*?"""', _dqString, _sqString]),
      keywords: {
        'as',
        'break',
        'class',
        'companion',
        'const',
        'continue',
        'data',
        'do',
        'else',
        'enum',
        'false',
        'for',
        'fun',
        'if',
        'in',
        'init',
        'interface',
        'internal',
        'is',
        'lateinit',
        'null',
        'object',
        'open',
        'out',
        'override',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'sealed',
        'super',
        'suspend',
        'this',
        'throw',
        'true',
        'try',
        'typealias',
        'val',
        'var',
        'vararg',
        'when',
        'while',
        'by',
        'constructor',
        'import',
        'tailrec',
        'inline',
        'reified',
        'crossinline',
        'noinline',
        'operator',
        'infix',
        'abstract',
        'final',
        'annotation',
        'external',
        'actual',
        'expect',
      },
      builtins: {
        'Int',
        'Long',
        'Double',
        'Float',
        'Boolean',
        'Char',
        'String',
        'Byte',
        'Short',
        'Unit',
        'Any',
        'Nothing',
        'List',
        'Map',
        'Set',
        'Array',
        'Pair',
        'Triple',
        'Sequence',
      },
    ),
    'swift': _spec(
      comments: _cComments,
      strings: _strings([_dqString]),
      keywords: {
        'associatedtype',
        'class',
        'deinit',
        'enum',
        'extension',
        'fileprivate',
        'func',
        'import',
        'init',
        'inout',
        'internal',
        'let',
        'open',
        'operator',
        'private',
        'precedencegroup',
        'protocol',
        'public',
        'rethrows',
        'return',
        'static',
        'struct',
        'subscript',
        'typealias',
        'var',
        'break',
        'case',
        'catch',
        'continue',
        'default',
        'defer',
        'do',
        'else',
        'fallthrough',
        'for',
        'guard',
        'if',
        'in',
        'repeat',
        'switch',
        'throw',
        'try',
        'where',
        'while',
        'as',
        'false',
        'is',
        'nil',
        'self',
        'super',
        'throws',
        'true',
        'any',
        'some',
        'async',
        'await',
        'actor',
        'nonisolated',
        'lazy',
        'weak',
        'unowned',
        'mutating',
        'convenience',
        'required',
        'override',
        'final',
        'indirect',
      },
      builtins: {
        'Int',
        'Double',
        'Float',
        'Bool',
        'String',
        'Character',
        'Array',
        'Dictionary',
        'Set',
        'Optional',
        'Any',
        'AnyObject',
        'Self',
        'Void',
        'Result',
        'Error',
        'Never',
        'UInt',
        'Int8',
        'Int16',
        'Int32',
        'Int64',
      },
    ),
    'go': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'break',
        'case',
        'chan',
        'const',
        'continue',
        'default',
        'defer',
        'else',
        'fallthrough',
        'for',
        'func',
        'go',
        'goto',
        'if',
        'import',
        'interface',
        'map',
        'package',
        'range',
        'return',
        'select',
        'struct',
        'switch',
        'type',
        'var',
        'true',
        'false',
        'nil',
        'iota',
      },
      builtins: {
        'int',
        'int8',
        'int16',
        'int32',
        'int64',
        'uint',
        'uint8',
        'uint16',
        'uint32',
        'uint64',
        'uintptr',
        'float32',
        'float64',
        'complex64',
        'complex128',
        'bool',
        'byte',
        'rune',
        'string',
        'error',
        'any',
        'comparable',
        'append',
        'cap',
        'close',
        'copy',
        'delete',
        'len',
        'make',
        'new',
        'panic',
        'print',
        'println',
        'recover',
      },
    ),
    'rust': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString]),
      keywords: {
        'as',
        'async',
        'await',
        'break',
        'const',
        'continue',
        'crate',
        'dyn',
        'else',
        'enum',
        'extern',
        'false',
        'fn',
        'for',
        'if',
        'impl',
        'in',
        'let',
        'loop',
        'match',
        'mod',
        'move',
        'mut',
        'pub',
        'ref',
        'return',
        'self',
        'static',
        'struct',
        'super',
        'trait',
        'true',
        'type',
        'unsafe',
        'use',
        'where',
        'while',
        'abstract',
        'become',
        'box',
        'do',
        'final',
        'macro',
        'override',
        'priv',
        'typeof',
        'unsized',
        'virtual',
        'yield',
        'try',
      },
      builtins: {
        'i8',
        'i16',
        'i32',
        'i64',
        'i128',
        'isize',
        'u8',
        'u16',
        'u32',
        'u64',
        'u128',
        'usize',
        'f32',
        'f64',
        'bool',
        'char',
        'str',
        'String',
        'Vec',
        'Option',
        'Result',
        'Box',
        'Self',
        'Some',
        'None',
        'Ok',
        'Err',
        'Rc',
        'Arc',
        'Cell',
        'RefCell',
        'HashMap',
        'HashSet',
        'BTreeMap',
        'Cow',
        'Pin',
        'Fn',
        'FnMut',
        'FnOnce',
      },
    ),
    'c': _spec(
      comments: _cComments,
      strings: _strings([_dqString, _sqString]),
      keywords: {
        'abstract',
        'as',
        'auto',
        'base',
        'bool',
        'break',
        'case',
        'catch',
        'char',
        'checked',
        'class',
        'const',
        'constexpr',
        'continue',
        'default',
        'delete',
        'delegate',
        'do',
        'double',
        'else',
        'enum',
        'event',
        'explicit',
        'extern',
        'false',
        'final',
        'finally',
        'fixed',
        'float',
        'for',
        'foreach',
        'friend',
        'get',
        'goto',
        'if',
        'implicit',
        'in',
        'inline',
        'int',
        'interface',
        'internal',
        'is',
        'lock',
        'long',
        'namespace',
        'new',
        'noexcept',
        'null',
        'nullptr',
        'operator',
        'out',
        'override',
        'params',
        'private',
        'protected',
        'public',
        'readonly',
        'ref',
        'register',
        'return',
        'sealed',
        'set',
        'short',
        'signed',
        'sizeof',
        'static',
        'static_assert',
        'struct',
        'switch',
        'template',
        'this',
        'throw',
        'true',
        'try',
        'typedef',
        'typeid',
        'typename',
        'union',
        'unsigned',
        'using',
        'var',
        'virtual',
        'void',
        'volatile',
        'while',
        'string',
        'record',
        'init',
        'required',
        'partial',
        'where',
        'when',
        'dynamic',
        'async',
        'await',
        'yield',
        'nameof',
        'typeof',
      },
      builtins: {
        'size_t',
        'ptrdiff_t',
        'FILE',
        'uint8_t',
        'uint16_t',
        'uint32_t',
        'uint64_t',
        'int8_t',
        'int16_t',
        'int32_t',
        'int64_t',
        'bool',
        'String',
        'List',
        'Dictionary',
        'Task',
        'ValueTuple',
      },
    ),
    'json': _spec(
      comments: _never,
      strings: _dqString,
      keywords: {'true', 'false', 'null'},
      annotation: false,
    ),
    'yaml': _spec(
      comments: _hashComment,
      strings: _strings([_dqString, _sqString]),
      keywords: {'true', 'false', 'null', 'yes', 'no', 'on', 'off'},
      annotation: false,
    ),
    'bash': _spec(
      comments: _hashComment,
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'if',
        'then',
        'else',
        'elif',
        'fi',
        'for',
        'while',
        'until',
        'do',
        'done',
        'case',
        'esac',
        'function',
        'in',
        'select',
        'time',
        'coproc',
        'echo',
        'cd',
        'export',
        'local',
        'readonly',
        'return',
        'exit',
        'shift',
        'source',
        'alias',
        'eval',
        'exec',
        'set',
        'unset',
        'declare',
        'typeset',
        'let',
        'read',
        'printf',
        'test',
        'trap',
        'wait',
        'true',
        'false',
        'break',
        'continue',
      },
      annotation: false,
    ),
    'sql': _spec(
      comments: r'--[^\n]*|/\*[\s\S]*?\*/',
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'select',
        'from',
        'where',
        'insert',
        'into',
        'values',
        'update',
        'set',
        'delete',
        'create',
        'table',
        'drop',
        'alter',
        'add',
        'join',
        'inner',
        'left',
        'right',
        'full',
        'outer',
        'on',
        'and',
        'or',
        'not',
        'null',
        'as',
        'order',
        'by',
        'group',
        'having',
        'limit',
        'offset',
        'union',
        'all',
        'distinct',
        'case',
        'when',
        'then',
        'else',
        'end',
        'exists',
        'in',
        'between',
        'like',
        'is',
        'primary',
        'key',
        'foreign',
        'references',
        'index',
        'view',
        'constraint',
        'default',
        'unique',
        'check',
        'cascade',
        'begin',
        'commit',
        'rollback',
        'transaction',
        'grant',
        'revoke',
        'true',
        'false',
        'count',
        'sum',
        'avg',
        'min',
        'max',
        'asc',
        'desc',
        'with',
        'recursive',
        'over',
        'partition',
        'returning',
      },
      caseInsensitiveKeywords: true,
      annotation: false,
    ),
    'html': _spec(
      comments: _htmlComment,
      strings: _strings([_dqString, _sqString]),
      tag: r'</?[A-Za-z][A-Za-z0-9:_-]*',
      keywords: const {},
      annotation: false,
    ),
    'generic': _spec(
      comments: '$_cComments|$_hashComment',
      strings: _strings([_dqString, _sqString, _backtickString]),
      keywords: {
        'if',
        'else',
        'for',
        'while',
        'do',
        'switch',
        'case',
        'default',
        'break',
        'continue',
        'return',
        'try',
        'catch',
        'finally',
        'throw',
        'throws',
        'new',
        'delete',
        'class',
        'struct',
        'enum',
        'interface',
        'function',
        'func',
        'def',
        'fn',
        'fun',
        'var',
        'let',
        'const',
        'static',
        'final',
        'void',
        'null',
        'nil',
        'none',
        'true',
        'false',
        'this',
        'self',
        'super',
        'import',
        'export',
        'from',
        'package',
        'include',
        'using',
        'namespace',
        'public',
        'private',
        'protected',
        'internal',
        'extends',
        'implements',
        'async',
        'await',
        'yield',
        'in',
        'of',
        'is',
        'as',
        'typeof',
        'instanceof',
        'and',
        'or',
        'not',
        'lambda',
        'pass',
        'raise',
        'with',
        'match',
        'where',
      },
    ),
  };
}

/// Compiled tokenization rules for one language family.
class _LangSpec {
  const _LangSpec({
    required this.pattern,
    required this.keywords,
    required this.builtins,
    required this.caseInsensitiveKeywords,
  });

  final RegExp pattern;
  final Set<String> keywords;
  final Set<String> builtins;
  final bool caseInsensitiveKeywords;
}

/// Memoization key for [CodeHighlighter.highlight].
class _CacheKey {
  const _CacheKey(this.language, this.code, this.theme, this.enabled);

  final String language;
  final String code;
  final CodeBlockTheme theme;
  final bool enabled;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is _CacheKey &&
          other.language == language &&
          other.code == code &&
          other.theme == theme &&
          other.enabled == enabled;

  @override
  int get hashCode => Object.hash(language, code, theme, enabled);
}
